In [12]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

K = keras.backend

# Chapter 12. Custom Models and Training with TensorFlow

## Using TensorFlow like NumPy

In [2]:
t = tf.constant([[1, 2., 3.], [4., 5. ,6.]])

2021-12-12 09:17:05.023529: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
t.shape

TensorShape([2, 3])

In [5]:
t.dtype

tf.float32

In [6]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [7]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [8]:
t + 1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [9]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [10]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

Or in keras, a limited subset is available:

In [11]:
K.square(K.transpose(t)) + 10

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11., 26.],
       [14., 35.],
       [19., 46.]], dtype=float32)>

In NumPy, pay attention to default dtype:

In [19]:
tf.constant([1., 2., 3.])

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [20]:
tf.constant(np.array([1., 2., 3.]))

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [21]:
tf.constant(np.array([1., 2., 3.]), dtype=tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

Type conversions need to be done manually since they can mean large performance hits:

In [22]:
tf.constant(1.) + tf.constant(2)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [23]:
tf.constant(1.) + tf.cast(tf.constant(2), tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

### Variables - mutable tensors

In [29]:
v = tf.Variable([[1., 2.], [3., 4.]])
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [30]:
v.assign(2 * v)
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 4.],
       [6., 8.]], dtype=float32)>

In [31]:
v[0,0].assign(5.)
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[5., 4.],
       [6., 8.]], dtype=float32)>

## Customizing Models and Training Algorithms